name: linter

on:
  pull_request:
    paths:
      - "**.py"

  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        $CONDA/bin/conda env update --file environmentCPU.yml --name touche
        $CONDA/bin/conda activate touche

    - name: flake8
      run: |
        pip install flake8
        flake8 src/ tests/ --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src/ tests/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: black
      run: |
        pip install black
        black src/ tests/

    - name: mypy
      run: |
        pip install mypy
        mypy src/ tests/