name: CI

on:
  pull_request:
    paths:
      - "**.py"

  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        $CONDA/bin/conda env update --file environmentCPU.yml --name base
    - name: flake8
      run: |
        $CONDA/bin/conda install flake8
        $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

