name: Tests

on:
  pull_request:
    paths:
      - "**.py"

  workflow_dispatch:

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Environment
      run: |
        $CONDA/bin/conda env update --file environmentCPU.yml --name base
    - name: keys
      shell: bash
      run: |
        gpg --quiet --batch --yes --decrypt --passphrase="$PASSPHRASE" \
        --output tests/input/keys.csv tests/input/keys.csv.gpg
      env:
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
    - name: unittest
      run: |
        python -m unittest discover -s tests/
